name: Run GPR

on:
  # runs daily at 5:05 AM EST
  schedule:
    - cron: '5 10 * * *'  
  workflow_dispatch:  # for manual runs

permissions:
  contents: write  # give write permission

jobs:
  fetch-gpr-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Debug repository structure
        run: ls -R  #verify script location

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get GPR data
        run: python gpr/get_gpr.py

      - name: Commit and push data
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add gpr/gpr_data.csv
          git commit -m 'Update data' || echo 'No changes to commit'
          git pull --rebase origin main
          git push
