name: Run VIX

on:
  # runs daily at 5:30 AM EST
  schedule:
    - cron: '30 10 * * *'  
  workflow_dispatch:  # for manual runs

permissions:
  contents: write  # give write permission

jobs:
  fetch-gscpi-data:
    runs-on: ubuntu-latest
    env:
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Debug repository structure
        run: ls -R  # verify script location
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
      
      - name: Get VIX data
        run: python fred_vix/get_vix.py
      
      - name: Commit and push data
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add fred_vix/vix_data.csv
          git commit -m 'Update data' || echo 'No changes to commit'
          git pull --rebase origin main
          git push
